name: Android-15-6.6

permissions:
  contents: write
  actions: write
  
on:
  workflow_call:
    inputs:
      kernelsu_variant:
        required: true
        type: string
      kernelsu_branch:
        required: true
        type: string
      use_zram:
        required: true
        type: boolean
      use_kpm:
        required: true
        type: boolean
      fast:
        required: true
        type: boolean
        
jobs:
  build-kernel:
    strategy:
      fail-fast: false
      matrix:
        include:
          - sub_level: "89"
            os_patch_level: "2025-06"
            
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      android_version: "android15"
      kernel_version: "6.6"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      use_zram: ${{ inputs.use_zram }}
      use_kpm: ${{ inputs.use_kpm }}
      fast: ${{ inputs.fast }}
