name: Android-15-6.6

permissions:
  contents: write
  actions: write
  
on:
  workflow_dispatch:
    inputs:
      kernelsu_variant:
        description: "Select KernelSU"
        required: true
        type: choice
        options:
          - Official
          - Next
          - MKSU
          - SukiSU
        default: SukiSU
      kernelsu_branch:
        description: "Select KSU branch"
        required: true
        type: choice
        options:
          - Stable
          - Dev
        default: Dev
      use_zram:
        description: 'Do you want to enable adding lz4+zstd?'
        required: true
        type: boolean
        default: false
      use_kpm:
        description: 'Do you want to enable the KPM function?'
        required: false
        type: boolean
        default: false
      fast:
        description: 'Compilation speedup (experimental): average speedup of 7 minutes'
        required: false
        type: boolean
        default: false
      use_Image:
        description: 'Do you want to enable repack boot.img?'
        required: false
        type: boolean
        default: false
        
jobs:
  build-kernel-a15-6-6-kernelsu-susfs:
    strategy:
      fail-fast: false
      matrix:
        include:
          - sub_level: "89"
            os_patch_level: "2025-06"
            
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      android_version: "android15"
      kernel_version: "6.6"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      use_zram: ${{ inputs.use_kpm }}
      use_Image: ${{ inputs.use_Image }}
      use_kpm: ${{ inputs.use_zram }}
      fast: ${{ inputs.fast }}
      onlyAk3: ${{ inputs.onlyAk3 }}
