name: Android 15 6.6
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  workflow_call:  # This allows this workflow to be called from another workflow
    inputs:
      make_release:
        required: true
        type: boolean
        default: true
      kernelsu_variant:
        required: true
        type: string
        default: SukiSu
      kernelsu_branch:
        required: true
        type: string
        default: Stable
      version:
        required: false
        type: string
        default: ""
      use_kpm:
        description: 'Do you want to enable the KPM function?'
        required: false
        type: boolean
        default: false
      fast:
        description: 'Compilation speedup (experimental): average speedup of 7 minutes'
        required: false
        type: boolean
        default: false
      onlyAk3:
        description: 'Only upload the AK3 compressed package? (No boot, faster download)'
        required: false
        type: boolean
        default: false


jobs:
  build-kernel-a15-6-6-kernelsu-susfs:
    strategy:
      fail-fast: false
      matrix:
        include:
          - sub_level: "56"
            os_patch_level: "2024-11"
          #- sub_level: "57"
          #  os_patch_level: "2024-12"
          #- sub_level: "58"
          #  os_patch_level: "2025-01"
          #- sub_level: "66"
          #  os_patch_level: "2025-02"
          #- sub_level: "77"
          #  os_patch_level: "2025-03"
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      make_release: ${{ inputs.make_release || false }}
      android_version: "android15"
      kernel_version: "6.6"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      kernelsu_variant: ${{ inputs.kernelsu_variant || 'Next' }}
      kernelsu_branch: ${{ inputs.kernelsu_branch || 'Dev' }}
      version: ${{ inputs.version || '' }}
      use_kpm: ${{ inputs.use_kpm }}
      fast: ${{ inputs.fast }}
      onlyAk3: ${{ inputs.onlyAk3 || false }}
