name: Build GKI

permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions
  
on:
  workflow_dispatch:
    inputs:
      kernelsu_variant:
        description: "Select KernelSU"
        required: true
        type: choice
        options:
          - Next
          - MKSU
          - SukiSU
        default: SukiSU
      kernelsu_branch:
        description: "Select KSU branch"
        required: true
        type: choice
        options:
          - Stable
          - Dev
        default: Dev
      use_kpm:
        description: 'Do you want to enable the KPM function?'
        required: true
        type: boolean
        default: true
      fast:
        description: 'Compilation speedup (experimental): average speedup of 7 minutes'
        required: true
        type: boolean
        default: true
      onlyAk3:
        description: 'Only upload the AK3 compressed package? (No boot, faster download)'
        required: false
        type: boolean
        default: true
jobs:

 build-kernel-a15-6-6:
    uses: ./.github/workflows/kernel-a15-6.6.yml
    secrets: inherit
    with:
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      use_kpm: ${{ inputs.use_kpm }}
      fast: ${{ inputs.fast }}
      onlyAk3: ${{ inputs.onlyAk3 }}
